#!/usr/bin/env python
# v2.1.0
import sys
from JAK.Application import JWebApp
from JAK import IPC
from JAK.Utils import Instance
from JAK.Widgets import InfoDialog


def get_file(file_type):
    from JAK.Widgets import FileChooserDialog
    window = Instance.retrieve("win")
    return FileChooserDialog(parent=window, file_type=file_type).choose_file()


def callback(src_file, extension, output):
    import pypandoc
    pypandoc.convert_file(src_file, extension, outputfile=output)
    InfoDialog(Instance.retrieve("win"), "All Done", f"Converted successfully to {output}")


def convert_file(convert_from, extension):
    import os, subprocess
    src_file = get_file(convert_from)
    if src_file:
        output_path = os.path.join(os.path.expanduser('~'), 'Documents/Converted-Files/')
        if not os.path.exists(output_path):
            os.mkdir(output_path)

        file_name = src_file.rsplit('/', 1)[1].split(".")[0]
        output = f"{output_path}{file_name}.{extension}"
        callback(src_file, extension, output)
        subprocess.run(["xdg-open", output_path])


class BindMenus:

    @staticmethod
    def docx_to_pdf():
        convert_file("docx", "pdf")

    @staticmethod
    def odt_to_pdf():
        convert_file("odt", "pdf")

    @staticmethod
    def docx_to_odt():
        convert_file("docx", "odt")

    @staticmethod
    def odt_to_docx():
        convert_file("odt", "docx")


IPC.Bind = BindMenus


def office():
    office_url = "https://office.live.com"
    try:
        if sys.argv[1] != "--dev":
            start = sys.argv[1]
        else:
            start = office_url
    except IndexError:
        start = office_url

    icon = "/usr/share/pixmaps/ms-office.png"

    adverts = "tpc.googlesyndication.com", "googleads.g.doubleclick.net", "tag.sp.advertising.com",\
              "banner.advertising.com", "cdn.bannerflow.com", "acdn.adnxs.com"

    tab_only_allow = "[a-z]*\.live.com", "www.office.com", "forms.office.com", "onedrive.", "d.docs.live.",\
                     "www.onenote.", "outlook.", "www.outlook.", "sway.office.com", "1drv.ms/",\
                     "to-do.microsoft.com/", "[a-z]*\.officeapps.live", "www.dropbox.com", \
                     "login.microsoftonline.com/", "onenote", "sway.com", "[a-z]*\.flow\.", "flow.",\
                     "[a-z-]+.sharepoint.com", "login.windows.net", "[a-z-]+.onmicrosoft.com", \
                     "teams.microsoft.com", "aka.ms", "myanalytics.microsoft.com/",\
                     "https://tasks.office.com", "app.powerbi.com/", "web.powerapps.com/",\
                     "security.microsoft.com/", "web.microsoftstream.com/", "whiteboard.microsoft.com/",\
                     "www.yammer.com/", "fluidpreview.office.net"

    css_hide = "a[href*='skype'], a[href*='bing'], a[href*='msn'], \
               a[href*='https://g.live.com'] {display:none !important;} \
               "

    deny = "account.microsoft", "support", "web.skype", "www.microsoft", "store.office.com", "msn.com", "bing.",\
           "products.office", "go.microsoft.com", "privacy."

    rules = {"WebBrowserTab": tab_only_allow, "WebBrowserWindow": deny, "block": adverts}

    menus = {"title": "Office", "entries": [\
         ["Office Home", office_url],\
         ["Excel", "https://office.live.com/start/Excel.aspx?"],\
         ["Word", "https://office.live.com/start/Word.aspx?"],\
         ["PowerPoint", "https://office.live.com/start/PowerPoint.aspx?"],\
         ["Forms", "https://forms.office.com"],\
         ["Sway", "https://sway.office.com"]]},\
    {"title": "Storage", "entries": [\
        ["OneDrive", "https://onedrive.live.com"],\
        ["DropBox", "https://www.dropbox.com"]]},\
    {"title": "Outlook", "entries": [\
        ["Email", "https://outlook.live.com"],\
        ["Calendar", "https://outlook.live.com/calendar/"],\
        ["People", "https://outlook.live.com/people/"],\
        ["Photos", "https://outlook.live.com/files/images/"],\
        ["Tasks", "https://outlook.live.com/owa/"]]},\
    {"title": "Others", "entries": [\
        ["Fluid Framework Preview", "https://fluidpreview.office.net/"],\
        ["Teams", "https://teams.microsoft.com"],\
        ["OneNote", "https://www.onenote.com"],\
        ["Flow", "https://flow.microsoft.com"]]},\
    {"title": "Convert Documents", "entries": [\
        ["DOCX to PDF", "docx_to_pdf()"],\
        ["DOCX to ODT", "docx_to_odt()"],\
        ["ODT to PDF", "odt_to_pdf()"],\
        ["ODT to DOCX", "odt_to_docx()"]]}

    webapp = JWebApp(
                     window={
                        "title": "Microsoft Office Online",
                        "icon": icon,
                        "menus": menus,
                     },

                     webview={
                        "webContents": start,
                        "addCSS": css_hide,
                        "urlRules": rules,
                        "cookiesPath": "microsoft",
                        "online": True
                    })
    return webapp
office().run()
