#!/usr/bin/env python
from JAK.Application import JWebApp


def skype():
    # v1.0.0
    url = "web.skype.com"

    rules = {"WebBrowserTab": url}
    
    webapp = JWebApp(title="Slack Online", web_contents=url, url_rules=rules, online=True, cookies_path="microsoft")

    return webapp


skype().run()
