#!/usr/bin/env python
from JAK.Application import JWebApp


def skype():
    # v2.1.0
    url = "web.skype.com"

    allow = url, "login.skype.com", "login.live.com"

    deny = "privacy.", "feedback."

    rules = {"WebBrowserTab": allow, "WebBrowserWindow": deny}

    webapp = JWebApp(
        window={
            "title": "Skype Online"
        },
        
        webview={
            "webContents": url, 
            "urlRules": rules, 
            "online": True, 
            "cookiesPath": "microsoft", 
            "MediaVideoCapture": True,
            "MediaAudioCapture": True
            }
        )
    return webapp
    

skype().run()
