#!/usr/bin/env python
from JAK.Application import JWebApp


def skype():
    # v1.0.0
    url = "web.skype.com"

    allow = url, "login.skype.com", "login.live.com"

    deny = "privacy.", "feedback."

    rules = {"WebBrowserTab": allow, "WebBrowserWindow": deny}

    webapp = JWebApp(title="Skype Online", web_contents=url, url_rules=rules, online=True, cookies_path="microsoft")

    return webapp


skype().run()
