#!/usr/bin/env python
from JAK.Application import JWebApp


def slack():
    # v2.1.0
    url = "slack.com"

    rules = {"WebBrowserTab": url}
    
    webapp = JWebApp(
        window={
            "title": "Slack Online",
         },
         webview={
             "webContents": url, 
             "urlRules": rules,
             "online": True
         }
        )

    return webapp


slack().run()

