#!/usr/bin/env python
from JAK.Application import JWebApp


def slack():
    # v1.0.1
    url = "slack.com"

    rules = {"WebBrowserTab": url}
    
    webapp = JWebApp(title="Slack Online", web_contents=url, url_rules=rules, online=True)

    return webapp


slack().run()
