#!/usr/bin/env python
from JAK.Application import JWebApp


def slack():
    # v1.0.0
    start = "https://slack.com"
    icon = "/usr/share/pixmaps/ms-office.png"
    ur = "slack.com", "slack.com"
    rules = {"WebBrowserTab": ur}
    
    webapp = JWebApp(title="Slack Online", web_contents=start, icon=icon, url_rules=rules, online=True)

    return webapp


slack().run()
