#!/usr/bin/env python
from JAK.Application import JWebApp


def whatsApp():
    # v2.1.0
    url = "web.whatsapp.com"

    user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0 Safari/537.36"

    allow = url, url

    rules = {"WebBrowserTab": allow}

    webapp = JWebApp(
        window={
            "title": "WhatsApp Online"
        },

        webview={
            "userAgent": user_agent,
            "online": True,
            "webContents": url,
            "urlRules": rules
        }
    )

    return webapp


whatsApp().run()
