#!/usr/bin/env python
from JAK.Application import JWebApp


def whats_app():
    # v1.0.1
    url = "web.whatsapp.com"

    user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.105 Safari/537.36"

    allow = url, url

    rules = {"WebBrowserTab": allow}

    webapp = JWebApp(title="WhatsApp Online", user_agent=user_agent, online=True, web_contents=url, url_rules=rules)

    return webapp

whats_app().run()
